export const CONSTANTS = {
    MESSAGE: 'message',
    COMPANYS: 'companys',
    CHATS: 'chats',
    VIEW: 'Ir a ver',
    DELETE: 'Eliminar',
    OFFICE_CHAT: 'OfficeChat',
    NEW_COMPANY: 'NewCompany',
    CONTACT: 'Contact',
    CHAT_ONLINE: 'Chat Online',
    LOGOUT: 'Logout',
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    MARINILLA_OFFICE_CHAT: 'Chat Oficina Marinilla',
    LOADING: 'Loading...',
    CONTACT_US: 'Contactanos',
    TICKET_INFO: 'Informacion de Tiquetes',
    CREATE_A_NEW_COMPANY: 'Crear una nueva empresa',
    CREATE_NEW_ACCOUNT: 'Crear Nueva Cuenta',
    SIGN_IN_WITH_AN_ACCOUNT: 'Ingresar con una cuenta',
    LOGIN: 'Login',
    ERROR_PAGE: '404 Error Page',
    FOUR_NUMBER: 4,
    CERO_NUMBER: 0,
    LOGO_URL: 'URL logo',
    NAME_COMPANY: 'Nombre Empresa',
    DESCRIPTION: 'Descripcion',
    COMPANY_URL: 'URL del sitio web de la empresa',
    SAVE: 'Guardar'
}
